from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from fastapi.responses import JSONResponse

class ProblemDetail(BaseModel):
    """
    RFC 9457 Problem Details for HTTP APIs (formerly RFC 7807)
    """
    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type."
    )
    title: str = Field(
        description="A short, human-readable summary of the problem type."
    )
    status: int = Field(
        description="The HTTP status code generated by the origin server for this occurrence of the problem."
    )
    detail: str = Field(
        description="A human-readable explanation specific to this occurrence of the problem."
    )
    instance: Optional[str] = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem."
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Trace ID for debugging (injected by middleware)."
    )
    errors: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="Detailed validation errors or specific field failures."
    )

def problem_response(
    status_code: int,
    title: str,
    detail: str,
    type: str = "about:blank",
    instance: Optional[str] = None,
    errors: Optional[List[Dict[str, Any]]] = None,
) -> JSONResponse:
    """Creates a JSONResponse matching the application/problem+json content type.
    Automatically injects request_id from structlog context."""
    import structlog
    context = structlog.contextvars.get_contextvars()
    request_id = context.get("request_id")
    
    content = {
        "type": type,
        "title": title,
        "status": status_code,
        "detail": detail,
    }
    
    if instance:
        content["instance"] = instance
    if request_id:
        content["request_id"] = request_id
    if errors:
        content["errors"] = errors
        
    return JSONResponse(
        status_code=status_code,
        content=content,
        media_type="application/problem+json"
    )

# Common problem types
PROBLEM_TYPES = {
    "validation_error": "https://api.spendsmart.internal/errors/validation",
    "authentication_error": "https://api.spendsmart.internal/errors/authentication",
    "authorization_error": "https://api.spendsmart.internal/errors/authorization",
    "not_found": "https://api.spendsmart.internal/errors/not-found",
    "conflict": "https://api.spendsmart.internal/errors/conflict",
    "internal_error": "https://api.spendsmart.internal/errors/internal",
}
